IdentityManager/Controllers/PermissionAreasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IdentityManager.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace IdentityManager.Controllers
{
    public class PermissionAreasController : Controller
    {
        private readonly StreamsContext _context;
        private readonly IConfiguration _conf;

        public PermissionAreasController(StreamsContext context, IConfiguration conf)
        {
            _context = context;            
            _conf = conf;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GetPermissionsAreas()
        {
            var list = _context.PermissionAreas.ToList<PermissionArea>();

            var jsonReturn = (from rec in list
                              select new
                              {
                                  Id = rec.Id,
                                  AreaName = rec.AreaName,
                                  Create = rec.Create,
                                  Read = rec.Read,
                                  Update = rec.Update,
                                  Delete = rec.Delete
                              }).ToList();

            return Json(jsonReturn);
        }
    }
}

IdentityManager/Controllers/UsersController.cs
using IdentityManager.Code.Interface;
using IdentityManager.Data;
using IdentityManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityManager.Controllers
{
    public class UsersController : Controller
    {
        private readonly StreamsContext _context;
        private readonly IELog _elog;
        private readonly IConfiguration _conf;
        private readonly IUser _user;
        public UsersController(StreamsContext context, IELog elog, IConfiguration conf, IUser user)
        {
            _context = context;
            _elog = elog;           
            _conf = conf;
            _user = user;
        }
        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Authentication");
            }
            return View();
        }

        [HttpGet]
        public IActionResult GetUsersList()
        {
            List<User> list = _user.GetSytemUsersList().Where(a=> a.IsActive == true && a.Username != null && a.Username != "").ToList<IdentityManager.Models.User>();
            var jsonReturn = (from rec in list
                              select new
                              {
                                  Id = rec.Id,
                                  Username = rec.Username,
                                  Forename = rec.Forename,
                                  Surname = rec.Surname,
                                  IsActive = rec.IsActive,
                                  IsSystemUser = rec.IsSystemUser, 
                                  AccessGroup = rec.AccessGroupName
                              }).ToList();

            return Json(jsonReturn);

        }
        [HttpGet]
        public IActionResult Edit(string id)
        {
            if(id != "")
            {
                
            }
            return View();
        }
    }
}

IdentityManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Identity and Access Manager</title>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-lg">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Identity and Access Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PermissionAreas" asp-action="Index">Permission Areas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="GetRolePermissions">Role Permissions</a>
                        </li>

                        }
                    </ul>
                </div>
                <div class="customer-rightheader">
                    @if (User.Identity.IsAuthenticated)
                    {
                    @using (Html.BeginForm("Logout", "Authentication", FormMethod.Post))
                        {
                    <div class="input-group pull-left">
                        @*@ViewBag.LoggedInUser*@
                        <button type="submit" class="btn btn-sm btn-primary "><i class="fas fa-user"></i>&nbsp;&nbsp;&nbsp;Sign out&nbsp;&nbsp;&nbsp;<i class="fas fa-sign-out-alt"></i></button>
                    </div>
                        }
                    }
                </div>
                <div>
                    <img src="~/images/TechnologyLogo.png" />
                </div>
            </div>
        </nav>
    </header>
    <div class="body-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <span style="color:#111;font-weight:normal;font-style:italic;" id="StreamsRelease">
                <a href="#" data-mdb-toggle="tooltip" title="Version  @ViewData["ReleaseVersion"]   Release:  @ViewData["ReleaseDate"]">Identity Manager</a>
            </span> -
            Copyright &copy;@DateTime.Now.Year Restore Technology, all rights reserved.
        </div>
    </footer>    
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>