IdentityManager/Controllers/UserPermissionController.cs
using IdentityManager.Data;
using IdentityManager.Models;
using IdentityManager.Models.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityManager.Controllers
{
    public class UserPermissionController : Controller
    {
        private readonly StreamsContext _context;
        private readonly IConfiguration _conf;
        private readonly IAccessGroupPermissions _permissions;

        public UserPermissionController(StreamsContext context, IAccessGroupPermissions permissions, IConfiguration conf)
        {
            _context = context;
            _permissions = permissions;
            _conf = conf;
        }
        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Authentication");
            }
            
            //Get User Permission
            return View();
        }
        [HttpGet]
        public IActionResult GetUsersPermissions(string UserId)
        {
            var roleid = _context.Contacts.ToList().Where(a => a.Username == UserId).First().AccessGroup;
            List<AccessGroupPermissions> list = _permissions.GetAllPermissions(roleid.ToString());            
            var jsonReturn = (from rec in list
                              select new
                              {
                                  Id = rec.Id,
                                  AreaName = rec.AreaName,
                                  Create = rec.Create,
                                  Read = rec.Read,
                                  Update = rec.Update,
                                  Delete = rec.Delete
                              }).ToList();

            return Json(jsonReturn);
        }
        [HttpGet]
        public IActionResult UserPermissions(string id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Authentication");
            }
            RolePermissionViewModel model = new RolePermissionViewModel();            
           
            //model.PermissionAreaList = GetPermissionAreas();
            ViewBag.PermissionAreaList = GetPermissionAreas();
            ViewBag.PermissionOptions = GetOptions();
            if (id != "")
            {                
                Contact contact = _context.Contacts.Where(a => a.Id == Guid.Parse(id)).First();
                model.RoleId = contact.AccessGroup;
                ViewBag.RoleName = _context.AccessGroups.Where(a => a.Id == model.RoleId).FirstOrDefault().Name.ToString();
            }
            return View(model);
        }
        
        public IActionResult GetPermissions(string roleid, int id)
        {
            AccessGroupPermissions permission = _permissions.GetRolePermissions(roleid,id);            
            return Json(permission);
        }
        public IEnumerable<SelectListItem> GetPermissionAreas()
        {
            List<SelectListItem> list = null;

            using (var context = new StreamsContext(_conf))
            {
                // Queries DB for list of categories by AccountID
                var query = (from ca in context.PermissionAreas                             
                             orderby ca.AreaName
                             select new SelectListItem { Text = ca.AreaName, Value = ca.Id.ToString() }).Distinct();
                list = query.ToList();
            }
            return list;
        }
        [HttpPost]
        public IActionResult SavePermissions(RolePermissionViewModel model)
        {
            RolePermission rolePermission = _context.RolePermissions.Where(a => a.Id == model.RecId).FirstOrDefault();

            //rolePermission.Create = Convert.ToBoolean(int.Parse(Request.Form["CreateValue"].ToString()));
            //rolePermission.Read = Convert.ToBoolean(int.Parse(Request.Form["ReadValue"].ToString()));
            //rolePermission.Update = Convert.ToBoolean(int.Parse(Request.Form["UpdateValue"].ToString()));
            //rolePermission.Delete = Convert.ToBoolean(int.Parse(Request.Form["DeleteValue"].ToString()));
            rolePermission.Create = model.CreateValue == true ? true : false;
            rolePermission.Read = model.ReadValue == true ? true : false;
            rolePermission.Update = model.UpdateValue == true ? true : false;
            rolePermission.Delete = model.DeleteValue == true ? true : false;
            _context.Update(rolePermission);
            _context.SaveChanges();

            return RedirectToAction("Index", "Users");
        }
        public IEnumerable<SelectListItem> GetOptions()
        {
            List<SelectListItem> list = new List<SelectListItem>();

            list.Add(new SelectListItem() { Text = "Yes", Value = "1" });
            list.Add(new SelectListItem() { Text = "No", Value = "0" });
            return list;
        }

    }
}

IdentityManager/Views/UserPermission/Index.cshtml
@{
    ViewData["Title"] = "User Permission";
}

<h3>User Permission</h3>
<link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet" />
<div class="container">
    <h3><small>Users</small></h3>
    <div class="form-group col-sm-4 pull-center">
        &nbsp;
    </div>
    <div class="form-group  pull-center">
        <table id="UsersPermissionDataTable" class="table dataTableServer table-striped table-bordered dt-responsive nowrap compact" cellspacing="0" width="40%" data-source="sorted">
            <thead>
                <tr class="tableheadercolourassetsorted">
                    <th style="display:none;">Id</th>
                    <th>Area</th>
                    <th>Create</th>
                    <th>Read</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="form-group col-sm-4 pull-center">
        &nbsp;
    </div>
</div>
<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/datatables/js/jquery.dataTables.js"></script>
<script src="~/js/Pages/UserPermission.js"></script>

IdentityManager/Views/UserPermission/UserPermissions.cshtml
@model IdentityManager.Models.RolePermissionViewModel
@{
    ViewData["Title"] = "User Permissions";
}
<style>
    .form-switch {
        padding-left: 3.5em;
    }
    .ms-1 {
        margin-left: ($spacer * .25) !important;
    }
    .ms-3 {
        margin-left: ($spacer * .75) !important;
    }
</style>

<div class="container">
    <div class="row">
        <div class="d-flex justify-content-start">
            <h3 class="text-center"><small>User Permissions</small></h3>
        </div>
    </div>
    <div class="ms-3 justify-content-left">
        <form asp-controller="UserPermission" asp-action="SavePermissions" method="post">
            <div class="row">
                <label class="col-lg-2">Role</label>
                <div class="col-lg-4">
                    <input asp-for="RoleId" hidden placeholder="Enter your name" autocomplete="off" class="form-control" />
                    <input id="RoleName" value="@ViewBag.RoleName" autocomplete="off" class="form-control" />
                </div>
            </div>
            <br />
            <div class="row">
                <label class="col-lg-2">Area</label>
                <div class="col-lg-4">
                    <select asp-for="AreaId" asp-items="(IEnumerable<SelectListItem>)ViewBag.PermissionAreaList" class="form-control form-select"></select>
                </div>
            </div>
            <br />
            <div class="row">
                <label class="col-lg-2">Create</label>
                <div class="col-lg-2 form-check form-switch">
                    <input asp-for="CreateValue" class="form-control form-check-input" type="checkbox" role="switch" id="CreateValue" />
                </div>
            </div>
            <div class="row">
                <label class="col-lg-2">Read</label>
                <div class="col-lg-2 form-check form-switch">
                    <input asp-for="ReadValue" class="form-control form-check-input" type="checkbox" role="switch" id="ReadValue" />
                </div>
            </div>
            <div class="row">
                <label class="col-lg-2">Update</label>
                <div class="col-lg-2 form-check form-switch">
                    <input asp-for="UpdateValue" class="form-control form-check-input" type="checkbox" role="switch" id="UpdateValue" />
                </div>
            </div>
            <div class="row">
                <label class="col-lg-2">Delete</label>
                <div class="col-lg-2 form-check form-switch">
                    <input asp-for="DeleteValue" class="form-control form-check-input" type="checkbox" role="switch" id="DeleteValue" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg-offset-4 col-lg-6 text-right">
                    <button type="submit" class="btn btn-primary float-lg-end">Save</button>
                </div>
            </div>
            <input asp-for="RecId" hidden autocomplete="off" class="form-control" />
            <script src="~/lib/jquery/jquery.min.js"></script>
            <script src="~/js/Pages/UserPermission.js"></script>
        </form>
    </div>
</div>